CREATE TABLE ARTICLES(
    MID INT PRIMARY KEY NOT NULL,
    TITLE TEXT NOT NULL,
    YEAR INT NOT NULL,
    VOLUME INT,
    NUMBER INT,
    PAGES1 INT,
    PAGES2 INT,
    MONTH INT,
    NOTE TEXT); 
