CREATE TABLE BOOKS(
    MID INT PRIMARY KEY NOT NULL,
    PUBLISHER INT NOT NULL,
    YEAR INT NOT NULL,
    VOLUME INT,
    NUMBER INT,
    SERIES TEXT,
    ADDRESS TEXT,
    EDITION INT,
    MONTH INT,
    NOTE TEXT,
    ISBN TEXT);
